markdown: kramdown
highlighter: rouge
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num
gems: [jekyll-paginate]


blog:
    name:         VERYYOUNG                                         # 博客名称
    description:  永远年轻，永远探索！                                 # 博客描述
    title:        永远年轻，永远探索！                  # 网页标题
    url:          http://veryyoung.me                               # 博客地址
    gitment:                                                        # Gitment 
        owner:  veryyoung
        repo:  veryyoung.github.io
        oauth: 
            client_id: 0da5b2d33965ff6ad68f
            client_secret: 2da6847a7db9b4c7cb48b055bb5c0b30b528d485

author:
    name:         veryyoung                                         # 作者名称
    email:        veryyoung.me@gmail.com                            # 邮箱地址
    weibo:        http://weibo.com/yangxi0ngwei                     # 微博地址
    github:       https://github.com/veryyoung                      # GitHub地址
    logo:         https://tpssl.weibo.cn/2536700194/180/5701775994/1 # logo地址